# Generated by Django 3.0.6 on 2020-06-20 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_image', models.ImageField(upload_to='question_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer', models.TextField(max_length=1000)),
                ('answer_time', models.DateTimeField(auto_now=True)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Question')),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account.id+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
