# Generated by Django 3.0.5 on 2020-05-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterField(
            model_name='answers',
            name='acc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account.id+', to=settings.AUTH_USER_MODEL),
        ),
    ]
