# Generated by Django 3.0.6 on 2020-06-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
    ]
